use amazon_sales_analysis;
-- ---------------------------
-- 10 Advanced Business Problems
-- ---------------------------

/*
1. Top Selling Products
Query the top 10 products by total sales value.
Challenge: Include product name, total quantity sold, and total sales value.
*/
select sub.product_id , p.product_name, sub.tot_qty, sub.tot_sales 
From (	
	select product_id, sum(quantity) tot_qty , round(sum(total_sales)) as tot_sales
	from order_items
	group by product_id
	order by tot_Sales desc
	limit 10 ) sub
join products p
on sub.product_id = p.product_id;


/*
2. Revenue by Category
Calculate total revenue generated by each product category.
Challenge: Include the percentage contribution of each category to total revenue.
*/

select  c.category_id, c.category_name,
		round(sum(ot.total_sales)) as total_sales,
        round(sum(ot.total_sales)*100.0/(select sum(total_sales) from order_items),2) as perc_contri
from order_items ot
join products p
on ot.product_id = p.product_id
join categories c
on p.category_id = c.category_id
group by c.category_id, c.category_name
order by perc_contri desc;


/*
3. Average Order Value (AOV)
Compute the average order value for each customer.
Challenge: Include only customers with more than 5 orders.
*/
select  o.customer_id,
		concat (c.first_name , ' ', c.last_name) as fname,
		round(sum(ot.total_sales)/count(o.customer_id),2) as AOV,
        count(o.customer_id) as cnt_orders
from order_items ot
join orders o
on ot.order_id = o.order_id
join customers c
on o.customer_id = c.customer_id
group by o.customer_id, concat (c.first_name , ' ', c.last_name)
having count(o.customer_id) > 5
order by AOV desc ;
/*
4. Monthly Sales Trend
Query monthly total sales over the past year.
Challenge: Display the sales trend, grouping by month, return current_month sale, last month sale!
*/
with cte as(
select  extract(month from o.order_date) as month,
		monthname(o.order_date) as month_name,
		round(sum(total_sales)) as curr_month_sale
from order_items ot
join orders o
on ot.order_id = o.order_id
group by extract(month from o.order_date) , monthname(o.order_date) 
order by month asc ) ,

cte2 as( 
select *,
		lag(curr_month_sale) over() as prev_month_sale
from cte )  

SELECT
    month,
    month_name,
    curr_month_sale,
    prev_month_sale,
    (curr_month_sale - prev_month_sale) AS mom_change,
    ROUND((curr_month_sale - prev_month_sale) * 100.0 / prev_month_sale, 2) AS mom_percentage_change
FROM cte2
ORDER BY month;

/*
5. Customers with No Purchases
Find customers who have registered but never placed an order.
Challenge: List customer details and the time since their registration.
*/
select c.customer_id,
		concat(c.first_name,' ',c.last_name) as name,
        c.state  
from customers 	c
left join orders o
on c.customer_id = o.customer_id
where o.customer_id is NULL;

/*
6. Least-Selling Categories by State
Identify the least-selling product category for each state & % contribution of the least-selling category within the state.
Challenge: Include the total sales for that category within each state.
*/
WITH state_sales AS (
    SELECT 
        c.state,
        ctg.category_name,
        SUM(ot.total_sales) AS total_sales
    FROM order_items ot
    JOIN orders o ON ot.order_id = o.order_id
    JOIN customers c ON o.customer_id = c.customer_id
    JOIN products p ON ot.product_id = p.product_id
    JOIN categories ctg ON p.category_id = ctg.category_id
    GROUP BY c.state, ctg.category_name
),
ranked AS (
    SELECT 
        state,
        category_name,
        total_sales,
        ROW_NUMBER() OVER (PARTITION BY state ORDER BY total_sales ASC) AS rn,
        round(sum(total_sales) OVER (PARTITION BY state)) AS state_total_sales
    FROM state_sales
)
SELECT 
    state,
    category_name AS least_selling_category,
    total_sales,
    state_total_sales,
    ROUND((total_sales / state_total_sales) * 100, 2) AS percentage_contribution
FROM ranked
WHERE rn = 1
ORDER BY state;

/*
7. Customer Lifetime Value (CLTV)
Calculate the total value of orders placed by each customer over their lifetime.
Challenge: Rank customers based on their CLTV.
*/
WITH customer_cltv AS (
    SELECT 
        c.customer_id as  customer_id,
        concat(c.first_name,' ',c.last_name) as customer_name ,
        ROUND(SUM(ot.total_sales)) AS cltv
    FROM order_items ot
    JOIN orders o 
        ON ot.order_id = o.order_id
    JOIN customers c 
        ON o.customer_id = c.customer_id
    GROUP BY c.customer_id, concat(c.first_name,' ',c.last_name)
)
SELECT 
    customer_id,
    customer_name,
    cltv,
    RANK() OVER (ORDER BY cltv DESC) AS cltv_rank
FROM customer_cltv
ORDER BY cltv DESC;



/*
8. Inventory Stock Alerts
Query products with stock levels below a certain threshold (e.g., less than 10 units).
Challenge: Include last restock date and warehouse information.
*/
SELECT 
	i.inventory_id,
	p.product_name,
	i.stock as current_stock_left,
	i.last_stock_date,
	i.warehouse_id
FROM inventory as i
join 
products as p
ON p.product_id = i.product_id
WHERE stock < 10 ;


/*
9. Most Returned Products
Query the top 10 products by the number of returns.
Challenge: Display the return rate as a percentage of total units sold for each product.
*/
select  p.product_id,
		p.product_name,
        sum(oi.quantity) as tot_units_sold,
        SUM(CASE WHEN o.order_status = 'Returned' THEN 1 ELSE 0 END) as total_returned,
		ROUND((SUM(CASE WHEN o.order_status = 'Returned' THEN 1 ELSE 0 END) / COUNT(*)) * 100,2) AS return_percentage
FROM order_items as oi
JOIN products as p
ON oi.product_id = p.product_id
JOIN orders as o
ON o.order_id = oi.order_id
group by p.product_id, p.product_name;


/*
10. Shipping Delays
Identify orders where the shipping date is later than 3 days after the order date.
Challenge: Include customer, order details, and delivery provider.
*/
SELECT 
    o.order_id,
    o.order_date,
    s.shipping_date,
    c.customer_id,
    s.shipping_provider
FROM orders o
JOIN shipping s 
    ON o.order_id = s.order_id
JOIN customers c
    ON o.customer_id = c.customer_id
WHERE DATEDIFF(s.shipping_date, o.order_date) > 3
ORDER BY o.order_date;

/*
11. Top Performing Sellers
Find the top 5 sellers based on total sales value.
*/
SELECT 
    s.seller_id,
    s.seller_name,
    SUM(oi.total_sale) AS total_revenue,
    COUNT(DISTINCT o.order_id) AS total_orders
FROM sellers s
JOIN orders o ON s.seller_id = o.seller_id
JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY s.seller_id, s.seller_name
ORDER BY total_revenue DESC
LIMIT 5;


/*
Q12: Product Profit Margin
Problem: Calculate profit margin percentage for each product using RANK window function.
*/
SELECT 
    product_id,
    product_name,
    price,
    cogs,
    (price - cogs) AS profit,
    ROUND(((price - cogs) / price) * 100, 2) AS profit_margin_percentage,
    RANK() OVER (ORDER BY ((price - cogs) / price) DESC) AS margin_rank
FROM products
WHERE price > 0
ORDER BY profit_margin_percentage DESC;



/*
Q13: Most Returned Products
Problem: Find products that have been returned most frequently.
*/
SELECT 
    p.product_id,
    p.product_name,
    sum(case when order_status = 'returned' then 1 else 0 end) AS return_count
FROM products p
JOIN order_items oi ON p.product_id = oi.product_id
JOIN orders o ON oi.order_id = o.order_id
GROUP BY p.product_id, p.product_name
ORDER BY return_count DESC
LIMIT 10;


/*
Q14: Orders Pending Shipment
Problem: Find orders where payment is done but product hasn't shipped yet.
*/
SELECT 
    o.order_id,
    o.order_date,
    p.payment_status,
    s.delivery_status
FROM orders o
JOIN payments p ON o.order_id = p.order_id
LEFT JOIN shipping s ON o.order_id = s.order_id
WHERE p.payment_status = 'Success'
  AND (s.delivery_status IS NULL OR s.delivery_status != 'Shipped')
ORDER BY o.order_date;


/*
15. Inactive Sellers
Identify sellers who haven't made any sales in the last 6 months.
Challenge: Show the last sale date and total sales from those sellers.

*/

WITH seller_sales AS (
    SELECT 
        seller_id,
        MAX(order_date) AS last_sale_date,
        COUNT(order_id) AS total_sales
    FROM orders
    GROUP BY seller_id
),
cutoff AS (
    SELECT DATE_SUB(MAX(order_date), INTERVAL 2 MONTH) AS cutoff_date
    FROM orders
)

SELECT 
    ss.seller_id,
    ss.last_sale_date,
    ss.total_sales
FROM seller_sales ss
CROSS JOIN cutoff c
WHERE ss.last_sale_date < c.cutoff_date
ORDER BY ss.last_sale_date;


/*
16. IDENTIFY customers into returning or new
if the customer has done more than 5 return categorize them as returning otherwise new
Challenge: List customers id, name, total orders, total returns
*/
WITH customer_summary AS (
    SELECT 
        customer_id,
        COUNT(*) AS total_orders,
        SUM(CASE WHEN order_status = 'Returned' THEN 1 ELSE 0 END) AS total_returns
    FROM orders
    GROUP BY customer_id
)

SELECT 
    cs.customer_id,
    CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
    cs.total_orders,
    cs.total_returns,
    CASE 
        WHEN cs.total_returns > 5 THEN 'returning' 
        ELSE 'new' 
    END AS customer_category
FROM customer_summary cs
JOIN customers c
    ON cs.customer_id = c.customer_id
ORDER BY cs.total_returns DESC;


/*
17. Top 5 Customers by Orders in Each State
Identify the top 5 customers with the highest number of orders for each state. 
Challenge: Include the number of orders and total sales for each customer.
*/
WITH ranked_customers AS (
    SELECT
        c.customer_id,
        c.full_name,
        c.state,
        COUNT(*) AS total_orders,
        ROUND(SUM(oi.total_sales), 2) AS total_sales,
        DENSE_RANK() OVER (
            PARTITION BY c.state 
            ORDER BY COUNT(*) DESC, SUM(oi.total_sales) DESC
        ) AS state_rank
    FROM order_items oi
    JOIN orders o ON oi.order_id = o.order_id
    JOIN customers c ON o.customer_id = c.customer_id
    GROUP BY c.customer_id, c.full_name, c.state
)
SELECT *
FROM ranked_customers
WHERE state_rank <= 5
ORDER BY state, state_rank;



/*
18. Top 10 product with highest decreasing revenue ratio compare to last year (2022) and current_year (2023)
Challenge: Return product_id, product name, category_name, 2022 revenue and 2023 revenue decrease ratio at end Round the res Note: Decrease ratio = cr-ls/ls 100 ts = current_year ls last year)
*/
WITH revenue_by_year AS (
    SELECT 
        p.product_id,
        p.product_name,
        c.category_name,
        YEAR(o.order_date) AS order_year,
        SUM(oi.total_sales) AS total_revenue
    FROM order_items oi
    JOIN orders o 
        ON oi.order_id = o.order_id
    JOIN products p 
        ON oi.product_id = p.product_id
    JOIN categories c 
        ON p.category_id = c.category_id
    GROUP BY p.product_id, p.product_name, c.category_name, YEAR(o.order_date)
),
rev_compare AS (
    SELECT 
        r22.product_id,
        r22.product_name,
        r22.category_name,
        r22.total_revenue AS revenue_2022,
        r23.total_revenue AS revenue_2023,
        ROUND(((r23.total_revenue - r22.total_revenue) / r22.total_revenue) * 100, 2) AS decrease_ratio
    FROM revenue_by_year r22
    JOIN revenue_by_year r23
        ON r22.product_id = r23.product_id
       AND r22.order_year = 2022
       AND r23.order_year = 2023
)
SELECT 
    product_id,
    product_name,
    category_name,
    revenue_2022,
    revenue_2023,
    decrease_ratio
FROM rev_compare
WHERE decrease_ratio < 0   -- ensures we only show decreasing products
ORDER BY decrease_ratio ASC   -- most decreased first (negative biggest)
LIMIT 10;

/*

19. Final Task
--Store Procedure
create a function as soon as the product is sold the the same quantity should reduced from inventory table
after adding any sales records it should update the stock in the inventory table based on the product and qty purchased
*/
DELIMITER $$

CREATE PROCEDURE add_sales(
    IN p_order_id INT,
    IN p_customer_id INT,
    IN p_seller_id INT,
    IN p_order_item_id INT,
    IN p_product_id INT,
    IN p_quantity INT
)
BEGIN
    DECLARE v_product_name VARCHAR(100);
    DECLARE v_price DECIMAL(10,2);
    DECLARE v_stock_count INT;

    -- Get product details & stock
    SELECT p.product_name, p.price, i.stock
    INTO v_product_name, v_price, v_stock_count
    FROM products p
    JOIN inventory i ON p.product_id = i.product_id
    WHERE p.product_id = p_product_id;

    -- Check stock
    IF v_stock_count < p_quantity THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = CONCAT('Not enough stock for product: ', v_product_name);
    END IF;

    -- Insert into orders table
    INSERT INTO orders (order_id, customer_id, seller_id, order_date, order_status)
    VALUES (p_order_id, p_customer_id, p_seller_id, CURDATE(), 'Confirmed');

    -- Insert into order_items table
    INSERT INTO order_items (order_item_id, order_id, product_id, quantity, price)
    VALUES (p_order_item_id, p_order_id, p_product_id, p_quantity, v_price);

    -- Reduce stock
    UPDATE inventory
    SET stock = stock - p_quantity
    WHERE product_id = p_product_id;

    SELECT CONCAT('Sale Added | Product: ', v_product_name, ' | Qty: ', p_quantity, ' | Stock Updated') AS message;

END $$

DELIMITER ;


